#!/bin/bash

source /tmp/debug/lib/lib.sh

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    usage
    exit
fi

argList="dlv dbgp xdebug allinone nuwa rsync upload"

flag=0

for arg in $argList
do
  if [ "$1" == $arg ]; then
    flag=1
  fi
done

if [ $flag == 0 ]; then
  usage
  exit
fi

plugin=$1

wget -S -N --no-cache --progress=bar "https://raw.githubusercontent.com/slyang-git/debug/main/${plugin}/install.sh?$(date +%s)" -O /tmp/debug/${plugin}_install.sh
chmod u+x /tmp/debug/${plugin}_install.sh

# exec plugin shell
bash -c /tmp/debug/${plugin}_install.sh
