#!/bin/bash

usage() {
cat 1>&2 <<EOF
       __     __               
  ____/ /__  / /_  __  ______ _
 / __  / _ \/ __ \/ / / / __  /
/ /_/ /  __/ /_/ / /_/ / /_/ / 
\__,_/\___/_.___/\__,_/\__, /  
                      /____/   
  

debug is a tool for setup and running Go/PHP/Java/Python/C++ debugger.

Usage:
debug [flag] [command]

[Flags]
-h, --help  Show this help message.

Available Commands:
-------------------
dlv      setup dlv debugger for Go. 
xdebug   setup xdebug debugger for PHP. 
upload   upload PHP source files to remote host  
rsync    setup rsyc server for sync go binary file.
dbgp     setup xdebug dbgpProxy for PHP.

For more information, please visit: 
EOF
}

source /tmp/debug/lib.sh

if [ "$1" == "-h" ] || [ "$1" == "--help" ]; then
    usage
    exit
fi

argList="dlv dbgp xdebug allinone nuwa rsync upload"

flag=0

for arg in $argList
do
  if [ "$1" == $arg ]; then
    flag=1
  fi
done

if [ $flag == 0 ]; then
  usage
  exit
fi

plugin=$1

wget --progress=dot https://raw.githubusercontent.com/slyang-git/debug/main/${plugin}/install.sh -O /tmp/debug/${plugin}_install.sh
chmod u+x /tmp/debug/${plugin}_install.sh
bash -c /tmp/debug/${plugin}_install.sh
